language: python
services:
  - mysql
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - python setup.py install
before_script:
  - mysql -e 'create database autobahn;'
  - psql -c 'create database autobahn' -U postgres
  - psql -c 'create table login (id SERIAL, login TEXT UNIQUE, fullname TEXT, password TEXT, tzname TEXT, PRIMARY KEY (id))' -U postgres autobahn
  - sqlrouter &
  - sqlbridge -e MYSQL -t 'com.mysql' -d 'db=autobahn user=root' &
  - sqlbridge -e PG -t 'com.pg' -d 'dbname=autobahn host=127.0.0.1 user=postgres' &
# command to run tests
script:
  - nosetests
  - sqlcmd -c operation -t 'com.pg' -q 'insert into login (password,fullname,login,tzname)values(%(p)s,%(f)s,%(l)s,%(t)s)' -a '{"p":"123test","f":"New User","l":"noob3","t":"America/Chicago"}'
  - sqlcmd -c query -t 'com.pg' -q 'insert into login (password,fullname,login,tzname)values(%(p)s,%(f)s,%(l)s,%(t)s) returning *' -a '{"p":"123test","f":"New User","l":"noob4","t":"America/Chicago"}'
  - sqlcmd -c query -t 'com.pg' -q 'select * from login'
  - sqlcmd -c watch -q 'testme'&
  - sqlcmd -c query -q "notify testme, 'this is a test'"
branches:
  only:
    - master
addons:
  postgresql: "9.3"
